name: CI/CD for Chat Service

on:
  push:
    paths:
      - 'chat/**'
  pull_request:
    paths:
      - 'chat/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/chat" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest-cov

      - name: Run tests with coverage
        run: |
          pytest --cov=chat --cov-fail-under=80 chat/tests/

      - name: Generate HTML coverage report
        run: |
          pytest --cov=chat --cov-report=html chat/tests/

      - name: Store coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/

  docker:
    runs-on: ubuntu-latest
    needs: build  # Ce job dépend du job de build précédent

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
